name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)

variables:
  - name: 'artifactory.Repository'
    value: 'build-Demo_SpringBoot'
  - name: 'projectName'
    value: 'Demo_Spring'
  - name: 'artifactName'
    value: 'demospring'


trigger:
  branches:
    include:
      - main

jobs:
  - job: CI
    displayName: 'Build / CI'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Gradle@2
        displayName: 'Gradle -> Build'
        inputs:
          gradleWrapperFile: '$(System.DefaultWorkingDirectory)/gradlew'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          tasks: 'clean build -x test'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          sonarQubeRunAnalysis: false
          spotBugsAnalysis: false

      - task: Gradle@2
        displayName: 'Gradle -> Unit Tests'
        inputs:
          gradleWrapperFile: '$(System.DefaultWorkingDirectory)/gradlew'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          tasks: 'test'
          publishJUnitResults: false
          codeCoverageToolOption: 'JaCoCo'
          codeCoverageClassFilesDirectories: 'build/classes/main/'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          sonarQubeRunAnalysis: false
          spotBugsAnalysis: false
        condition: succeeded()
      